FileVersion = 1
Projects = {AdventOfCodeBeef = {Path = "."}}

[Workspace]
StartupProject = "AdventOfCodeBeef"

[Configs.Release.Win64]
BfSIMDSetting = "SSE41"
RuntimeKind = "Reduced"
ReflectKind = "Minimal"
